/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yachat;

/**
 *
 * @author yashi
 */
public class ChatWindow extends javax.swing.JFrame {

    /**
     * Creates new form ChatWindow
     */
    
    public MainWindow mw;
    
    public ChatWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sel_emo = new javax.swing.JComboBox();
        txt_sent = new javax.swing.JTextField();
        btn_sent = new javax.swing.JButton();
        lbl_text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sel_emo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "正常", "微笑" }));
        getContentPane().add(sel_emo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 100, 30));

        txt_sent.setText("发送的文本");
        txt_sent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_sentKeyPressed(evt);
            }
        });
        getContentPane().add(txt_sent, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 690, 1080, 30));

        btn_sent.setText("发送");
        getContentPane().add(btn_sent, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 690, 100, 30));

        lbl_text.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_text.setForeground(new java.awt.Color(0, 0, 0));
        lbl_text.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_text.setText("请稍等一下。");
        lbl_text.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lbl_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 1200, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_sentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sentKeyPressed
        char nowKey = evt.getKeyChar();
        if (nowKey == '\n') {
            this.mw.outMsg(txt_sent.getText());
            txt_sent.setText("");
        }
    }//GEN-LAST:event_txt_sentKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatWindow().setVisible(true);
            }
        });
    }
    
    public void inMsg(String msg) {
        lbl_text.setText(msg);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sent;
    private javax.swing.JLabel lbl_text;
    private javax.swing.JComboBox sel_emo;
    private javax.swing.JTextField txt_sent;
    // End of variables declaration//GEN-END:variables
}
